### ISSUE TITLE
An error occurred. while playing video

### ISSUE THREAD

**Issue by zaasmi** [Jenkler/nodebb-plugin-video-embed#1]
An error occurred. Please try again later. (Playback ID: hHtvkstKGlwjxMmu)
Learn More

**Comment by zaasmi** [comment]
<p dir="auto"><div class="video-embed"><iframe src="//www.youtube.com/embed/?list=WLiFXMDHfX4" width="640" height="360"></iframe></div></p>
 
"/?list" creates a problem to load a short url copy from YouTube player

**Comment by Couby** [comment]
@Jenkler I confirm the plugin is broken :( .
It doesn't work with short urls proposed by Youtube, and these are the most used by people.
Possible to simply replace `?list` by `?watch` to simply have something that works in any case ?

**Comment by Jenkler** [comment]
This plugin must match both the list and single case of a youtube movie. I dont have time to take a look at it now but plz make a patch that works in all the cases and will check it out and patch this script later.

You need to paste the linke like this:
https://www.youtube.com/watch?v=WLiFXMDHfX4
and https://www.youtube.com/watch?list=<listid>

for it to work at the moment.

**Comment by Jenkler** [comment]
This is now fixed
